/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class merck_org_drawroto_NDKUtils */

#ifndef _Included_merck_org_drawroto_NDKUtils
#define _Included_merck_org_drawroto_NDKUtils
#ifdef __cplusplus
extern "C" {
#endif
  void  Java_merck_org_drawroto_NDKUtils_getEdge(JNIEnv *env, jobject thizz, jobject bitmap);

#ifdef __cplusplus
}
#endif
#endif
